version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - run: 
          name: Installing firebase tools
          command: sudo npm install -g firebase-tools
      - run:
          name: Deploying in Firebase
          command: firebase deploy --token "$FIREBASE_DEPLOY_TOKEN"
workflows:
    deploy:
      jobs:
        - deploy:
            filters:
              branches:
                only:
                  - master
